cart/views.py
from flask import session, url_for, render_template, flash, request, Blueprint

from cart.form import UpdateCartForm, AddItemToCartForm
from user.models import Product
from utils.is_url_safe import if_url_is_safe_redirect
from utils.process_shipping_fee import process_shipping_fee


cart_app = Blueprint('cart_app', __name__, url_prefix="/cart")


@cart_app.route("product/quick/add/<int:product_id>")
def add_one_item_to_cart(product_id):

    _add_to_cart_helper(product_id, quantity=1)
    flash("An item has been added to your shopping cart")

    return if_url_is_safe_redirect(request.referrer, url_to_redirect_to=request.referrer)


@cart_app.route("/add/<int:product_id>", methods=["POST"])
def add_to_cart(product_id):

    form = AddItemToCartForm()

    if form.validate_on_submit():

        if Product.query.filter_by(id=product_id).first().stock:
            _add_to_cart_helper(product_id, form.quantity.data)

    return if_url_is_safe_redirect(url_for('home_app.home'), route_func_name_to_redirect_to='home_app.home')


def _update_session_with_num_of_items_in_cart(item_num):

    if "cart" in session and "num_of_items" in session:
        session["num_of_items"] += item_num
    else:
        session["num_of_items"] = item_num
    session.modified = True


def _add_to_cart_helper(product_id, quantity, update=False):
    """_add_to_cart_helper(str, int, boolean) -> return None

      The add_to_cart_helper provides additional functionality to
      cart by adding items to the cart. The helper first checks if
      the item already exists in the cart. If it does it increments or decrements the
      quantity of items by the amount the user has chosen.

      If the item does not exists then it adds a item with a single quantity to cart.
      If the update "parameter" is set to true it allows the user to decrement the amount
      of items in the cart

      :parameter
        :product_id: The product id for the item
        :quantity: The number of items for the items.
        :update: Allows the user update the amount in their cart

    """

    if "cart" not in session:
        session["cart"] = {product_id: {"id": product_id, "quantity": quantity}}
    elif "cart" in session and not update and session["cart"].get(str(product_id)):
        session["cart"][str(product_id)]["quantity"] += quantity
    elif "cart" in session and update and session["cart"].get(str(product_id)):
       _update_cart_quantity(product_id, new_quantity=quantity)
    else:
        session["cart"].update({str(product_id): {"id": product_id, "quantity": quantity}})

    if not update:
        _update_session_with_num_of_items_in_cart(quantity)
    session.modified = True


def _update_cart_quantity(product_id, new_quantity):

    current_quantity = session["cart"][str(product_id)]["quantity"]
    difference = abs(current_quantity - new_quantity)

    if current_quantity > new_quantity:

        session["num_of_items"] -= difference
    else:
        session["num_of_items"] += difference

    session["cart"][str(product_id)]["quantity"] = new_quantity
    session.modified = True


@cart_app.route("/remove/item/<product_id>")
def remove_item_from_cart(product_id):

    session["num_of_items"] -= session["cart"][str(product_id)]["quantity"]

    del session["cart"][str(product_id)]

    session.modified = True

    return if_url_is_safe_redirect(url_for('cart_app.cart'), route_func_name_to_redirect_to='cart_app.cart')


@cart_app.route('/')
def cart():

    grand_total = 0
    products = []
    form = UpdateCartForm()
    num_of_items_in_cart = 0

    for product_id in session.get("cart", ""):
        product = Product.query.filter_by(id=int(product_id)).first()
        quantity = session["cart"][str(product_id)]['quantity']
        product.live = True
        total = quantity * product.price
        num_of_items_in_cart += quantity
        grand_total += total

        items = {"name": product.name, "price": product.price, "image": product.image, "quantity": quantity,
                         "total": round(total, 2), "id": product.id, "stock": product.stock}

        if items not in products:
            products.append(items)

    session["grand_total"] = grand_total
    session["products"] = products
    session.modified = True
    shipping_cost, shipping_fee = process_shipping_fee(grand_total)

    return render_template('cart/cart.html', cart_items=products, grand_total=round(grand_total, 2),
                           shipping_costs=shipping_cost, shipping_fee=shipping_fee, total_items=len(products), form=form)


@cart_app.route("/update/cart-quantity/<int:product_id>/", methods=["POST"])
def update_cart(product_id):

    form = UpdateCartForm()

    if form.validate_on_submit():
        _add_to_cart_helper(product_id, form.quantity.data, update=True)

    return if_url_is_safe_redirect(url_for('cart'), route_func_name_to_redirect_to='cart')

checkout/views.py
from secrets import token_hex

from flask import session, Blueprint, url_for, render_template, redirect, abort

from create_app import db
from checkout.form import CheckOutForm
from user.models import User, Order, Product
from utils.is_url_safe import is_safe_url
from utils.process_shipping_fee import _is_shipping_free

checkout_app = Blueprint("checkout_app", __name__, url_prefix="/checkout")

_SHIPPING_FEE = 50


@checkout_app.route('/', methods=["GET", "POST"])
def checkout():

    form = CheckOutForm()

    if form.validate_on_submit():
        reference_num = token_hex(15)
        user = User()
        form.populate_obj(obj=user)
        user.payment_status = "PENDING"
        user.reference_num = reference_num

        _add_all_bought_item_in_session_to_user_obj(user)

        if not is_safe_url(url_for('order_completion.app.order_completion', reference_number=reference_num)):
            abort(404)
        return redirect(url_for('order_completion_app.order_completion', reference_number=reference_num))

    return render_template('checkout/checkout.html', form=form, is_shipping_cost_free=_is_shipping_free)


def _add_all_bought_item_in_session_to_user_obj(user):

    for item in session["products"]:
        user_order = Order(quantity=item["quantity"], product_id=item["id"])
        user.items.append(user_order)
        Product.query.filter_by(id=item["id"]).update({'stock': Product.stock - item["quantity"]})

        if not _is_shipping_free(session.get("grand_total")):
            user_order.total_order = round(session["grand_total"] + _SHIPPING_FEE, 2)
        else:
            user_order.total_order = session["grand_total"]

    db.session.add(user)
    db.session.commit()
    _clear_cart_session()


def _clear_cart_session():
    """Clears all items that is related to the item's bought in the cart"""
    session.pop("cart")
    session.pop("grand_total")
    session.pop("products")
    session.pop("num_of_items")
    session.modified = True

product/views.py
from flask import Blueprint, render_template

from product.forms import AddProductToCartForm
from product.type import ITEM_TYPES
from user.models import Product

product_app = Blueprint('product_app', __name__, url_prefix="/product")

_PER_PAGE = 16


@product_app.route('/<int:product_id>', methods=["GET", "POST"])
def product(product_id):

    product = Product.query.get_or_404(product_id)
    return render_template('products/view-product.html', product=product, form=AddProductToCartForm())


@product_app.route("/trousers/<int:page_number>")
@product_app.route("/trousers")
def get_trousers(page_number=1):

    trousers = Product.query.filter(Product.type == ITEM_TYPES["TROUSERS"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                         page=page_number,
                                                                                                         error_out=False)
    return render_template("products/trousers.html", trousers=trousers, page_number=page_number)


@product_app.route("/tops/<int:page_number>")
@product_app.route("/tops")
def get_tops(page_number=1):

    tops = Product.query.filter(Product.type == ITEM_TYPES["TOPS"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                 page=page_number,
                                                                                                 error_out=False)
    return render_template("products/tops.html", tops=tops, page_number=page_number)


@product_app.route("/sports/wear/<page_number>")
@product_app.route("/sports/wear")
def get_sports_wear(page_number=1):

    sports_wear = Product.query.filter(Product.type == ITEM_TYPES["SPORTS_WEAR"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                               page=page_number,
                                                                                                               error_out=False)
    return render_template("/products/sports_wear.html", sports_wear=sports_wear, page_number=page_number)


@product_app.route("/lingerie/<int:page_number>")
@product_app.route("/lingerie")
def get_lingerie(page_number=1):

    lingeries = Product.query.filter(Product.type == ITEM_TYPES["LINGERIE"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                          page=page_number,
                                                                                                          error_out=False)
    return render_template("products/lingerie.html", lingeries=lingeries, page_number=page_number)


@product_app.route("/shoes/<int:page_number>")
@product_app.route("/shoes")
def get_shoes(page_number=1):
    shoes = Product.query.filter(Product.type == ITEM_TYPES["SHOES"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                   page=page_number, error_out=False)
    return render_template("products/shoes.html", shoes=shoes, page_number=page_number)


@product_app.route("/hoodies/<int:page_number>")
@product_app.route("/hoodies")
def get_hoodies(page_number=1):
    hoodies = Product.query.filter(Product.type == ITEM_TYPES["HOODIES"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                       page=page_number, error_out=False)
    return render_template("products/hoodies.html", hoodies=hoodies, page_number=page_number)


@product_app.route("/hats/<int:page_number>")
@product_app.route("/hats")
def get_hats(page_number=1):
    hats = Product.query.filter(Product.type == ITEM_TYPES["HATS"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                 page=page_number, error_out=False)
    return render_template("products/hats.html", hats=hats, page_number=page_number)

templates/cart/cart.html
{% extends "base.html" %}

{% block title %}Cart | Trendy Fashion Store{% endblock %}

{% block body %}
<div class="row">
	<div class="col-lg-8">
		<h3 class="bold">
			<i class="glyphicon glyphicon-shopping-cart"></i> Your Shopping Cart
		</h3>

		<div class="panel panel-primary">
			<div class="panel-body">

                {% if not cart_items %}
                    <p>
                        <strong>No items in your cart</strong>
                    </p>
                {% endif %}
                {% for cart_item in cart_items %}

                    {% from "__formhelpers.html" import render_field %}
                    <form action="{{ url_for('cart_app.update_cart', product_id=cart_item.id) }}" method="POST" role="form">

                         {{ form.csrf_token() }}
                    <div class="row">


                        <div class="col-lg-3">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="thumbnail thumbnail-q">
                                    <a href="{{ url_for('product_app.product', product_id=cart_item.id) }}">
                                        <img src="{{ url_for('static', filename='imgs/' + cart_item['image']) }}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <a href="{{ url_for('product_app.product', product_id=cart_item.id) }}">
                                <h4 class="bold">{{ cart_item.name.title() }}</h4>
                            </a>
                            <p>&pound;{{ cart_item.price }}</p>
                            <br />
                            <p>
                                <button type="button" class="btn btn-danger btn-xs">
                                    <a href="{{ url_for('cart_app.remove_item_from_cart', product_id=cart_item.id) }}">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                </button>
                            </p>

                        </div>
                        <div class="col-lg-2">
                            <p>
                                 {{ render_field(form.quantity, **{"class": "form-control", "id": "quantity_active",
                                                                  "autocomplete": "off", "value": cart_item.quantity,
                                                                  "step": "1", "min": "1", "max": cart_item["stock"], "type": "number"})
                                                }}

                            </p>
                        </div>
                        <div class="col-lg-2">
                            <h4>Total</h4>
                            <p>
                                <strong>&pound;{{ cart_item['total']  }}</strong>
                            </p>

                        </div>

                        <div class="col-lg-2">
                            <h4>Update</h4>
                            <p>
                              <button type="submit" class="btn btn-danger btn-sm" >
                                <i class="glyphicon glyphicon-shopping-cart"></i> Update Cart
                            </button>
                            </p>


                        </div>


                    </div>
                  </form>


                {% endfor %}



			</div>
		</div>
	</div>

	<div class="col-lg-4">
		<h3 class="bold">
			<i class="glyphicon glyphicon-th-list"></i> Cart Summary
		</h3>

		<div class="panel panel-primary">
			<div class="panel-body">
				Current Cart Value
			</div>
			<ul class="list-group">


				<li class="list-group-item">
					<p>
						{{ session.num_of_items }} Items <strong class="pull-right">&pound;{{ grand_total }}</strong>
					</p>

                     {% if shipping_costs %}
					    <p>
						Free shipping on items because you spent over <em>&pound;100</em><strong class="pull-right"></strong>
					    </p>
                    {% else %}
                        <p>
						You do not qualify for free shipping. You must spend over &pound;100 to qualify
                            <strong class="pull-right"></strong>
					    </p>
                    {% endif %}
				</li>
				<li class="list-group-item">

                    {% if not shipping_costs %}
                        <p>Grand Total <strong class="pull-right">&pound;{{ grand_total }}</strong></p>
                    {% elif session.num_of_items == 0 %}
                        <p>&pound;50 shipping fee will be added if you do not spend &pound;100 or more
                            <strong class="pull-right"></strong></p>
                         <p>Total <strong class="pull-right">&pound;0</strong></p>
                    {% else %}
                         <p>&pound;50 shipping fee added<strong class="pull-right"></strong></p>
                         <p>Total <strong class="pull-right">&pound;{{ shipping_fee }}</strong></p>
                    {% endif %}
                </li>
			</ul>
			<div class="panel-footer">
				<a href="{{ url_for('home_app.home') }}" class="btn btn-primary btn-sm">
					Continue shopping <i class="glyphicon glyphicon-chevron-left"></i>
				</a>
                <a href="{{ url_for('checkout_app.checkout') }}" class="btn btn-primary btn-sm">
					Checkout <i class="glyphicon glyphicon-chevron-right"></i>
				</a>

			</div>
		</div>
	</div>
</div>
{% endblock %}