admin/views.py
from os.path import join
from time import time as time_stamp
from flask import Blueprint, session, url_for, render_template, flash, abort
from sqlalchemy import desc
from werkzeug.utils import redirect, secure_filename

from admin.form import AdminLoginForm
from admin.model import AdminLogin
from product.forms import ProductForm
from settings import UPLOAD_DIR
from user.models import Product, User, Order
from utils.decorators import is_user_already_logged_in, is_admin
from utils.is_url_safe import is_safe_url, if_url_is_safe_redirect
from utils.passwd import Password

from create_app import db

admin_app = Blueprint('admin_app', __name__, url_prefix="/admin")


_PER_PAGE = 16


@admin_app.route("/login", methods=["GET", "POST"])
@is_user_already_logged_in
def admin_login():
    form = AdminLoginForm()
    error = False

    if form.validate_on_submit():
        user = AdminLogin.query.filter_by(user="admin").first()

        if user and "admin" == form.username.data.lower() and Password.check_password(form.password.data, user.password):
            session["admin"] = "admin"
            return redirect(url_for("home_app.home"))

        error = True

    return render_template("admin/admin_login.html", form=form, error=error)


@admin_app.route('/add', methods=["GET", "POST"])
@is_admin
def add():

    form = ProductForm()

    if form.validate_on_submit():
        file_name = str(time_stamp()) + secure_filename(form.image.data.filename)
        img_path = join(UPLOAD_DIR, file_name)

        product = Product(name=form.name.data, price=form.price.data, stock=form.stock.data,
                          description=form.description.data, image=file_name, type=form.type.data, live=True)

        db.session.add(product)
        db.session.commit()
        form.image.data.save(img_path)

        return if_url_is_safe_redirect(url_for('admin_app.admin'), route_func_name_to_redirect_to='admin_app.add')
    return render_template('admin/add-product.html', admin=True, form=form)


@admin_app.route("/<int:page_number>")
@admin_app.route('/')
def admin(page_number=1):

    products = Product.query.filter(Product.live==True).paginate(per_page=_PER_PAGE, page=page_number, error_out=False)
    available_stocks = Product.query.filter(Product.stock > 0).count()
    pending_orders = User.query.filter(User.payment_status == "PENDING").count()
    completed_orders = User.query.filter(User.payment_status =="Complete").count()
    out_of_stock = abs(products.total - available_stocks)
    users = User.query.order_by(desc(User.id)).paginate(per_page=_PER_PAGE, page=page_number, error_out=False)

    return render_template('admin/home.html', admin=True, products=products, out_of_stock=out_of_stock,
                           available_stocks=available_stocks, users=users, page_number=page_number,
                           pending_orders=pending_orders, completed_orders=completed_orders)


@admin_app.route("/delete/<int:page_number>")
@admin_app.route("/delete/<int:product_id>")
def delete_item(product_id, page_number=1):

    product = Product.query.get(product_id)
    product.live = False
    db.session.add(product)
    db.session.commit()

    flash("The item has been remove from the database")

    if not is_safe_url(url_for("home_app.home", page_number=page_number)):
        abort(404)
    return redirect(url_for("home_app.home", page_number=page_number))


@admin_app.route("/complete/<order_id>/<page_number>")
def complete_order(order_id, page_number):

    order = Order.query.filter_by(id=order_id).first()

    if order.user.payment_status != "Complete":
        order.user.payment_status = "Complete"

        db.session.add(order)
        db.session.commit()
    return redirect(url_for("admin_app.admin", page_number=page_number))


@admin_app.route('/product/<int:user_id>')
def view_order(user_id):

    user = User.query.filter_by(id=user_id).first_or_404()
    return render_template('admin/view-product.html', admin=True, user=user, user_id=user_id)


@admin_app.route("/logout")
def admin_logout():

    if session.get("admin"):
        del session["admin"]
    return redirect(url_for("home_app.home"))

cart/views.py
from flask import session, url_for, render_template, flash, request, Blueprint

from cart.form import UpdateCartForm, AddItemToCartForm
from user.models import Product
from utils.is_url_safe import if_url_is_safe_redirect
from utils.process_shipping_fee import process_shipping_fee


cart_app = Blueprint('cart_app', __name__, url_prefix="/cart")


@cart_app.route("product/quick/add/<int:product_id>")
def add_one_item_to_cart(product_id):

    _add_to_cart_helper(product_id, quantity=1)
    flash("An item has been added to your shopping cart")

    return if_url_is_safe_redirect(request.referrer, url_to_redirect_to=request.referrer)


@cart_app.route("/add/<int:product_id>", methods=["POST"])
def add_to_cart(product_id):

    form = AddItemToCartForm()

    if form.validate_on_submit():

        if Product.query.filter_by(id=product_id).first().stock:
            _add_to_cart_helper(product_id, form.quantity.data)

    return if_url_is_safe_redirect(url_for('home_app.home'), route_func_name_to_redirect_to='home_app.home')


def _update_session_with_num_of_items_in_cart(item_num):

    if "cart" in session and "num_of_items" in session:
        session["num_of_items"] += item_num
    else:
        session["num_of_items"] = item_num
    session.modified = True


def _add_to_cart_helper(product_id, quantity, update=False):
    """_add_to_cart_helper(str, int, boolean) -> return None

      The add_to_cart_helper provides additional functionality to
      cart by adding items to the cart. The helper first checks if
      the item already exists in the cart. If it does it increments or decrements the
      quantity of items by the amount the user has chosen.

      If the item does not exists then it adds a item with a single quantity to cart.
      If the update "parameter" is set to true it allows the user to decrement the amount
      of items in the cart

      :parameter
        :product_id: The product id for the item
        :quantity: The number of items for the items.
        :update: Allows the user update the amount in their cart

    """

    if "cart" not in session:
        session["cart"] = {product_id: {"id": product_id, "quantity": quantity}}
    elif "cart" in session and not update and session["cart"].get(str(product_id)):
        session["cart"][str(product_id)]["quantity"] += quantity
    elif "cart" in session and update and session["cart"].get(str(product_id)):
       _update_cart_quantity(product_id, new_quantity=quantity)
    else:
        session["cart"].update({str(product_id): {"id": product_id, "quantity": quantity}})

    if not update:
        _update_session_with_num_of_items_in_cart(quantity)
    session.modified = True


def _update_cart_quantity(product_id, new_quantity):

    current_quantity = session["cart"][str(product_id)]["quantity"]
    difference = abs(current_quantity - new_quantity)

    if current_quantity > new_quantity:

        session["num_of_items"] -= difference
    else:
        session["num_of_items"] += difference

    session["cart"][str(product_id)]["quantity"] = new_quantity
    session.modified = True


@cart_app.route("/remove/item/<product_id>")
def remove_item_from_cart(product_id):

    session["num_of_items"] -= session["cart"][str(product_id)]["quantity"]

    del session["cart"][str(product_id)]

    session.modified = True

    return if_url_is_safe_redirect(url_for('cart_app.cart'), route_func_name_to_redirect_to='cart_app.cart')


@cart_app.route('/')
def cart():

    grand_total = 0
    products = []
    form = UpdateCartForm()
    num_of_items_in_cart = 0

    for product_id in session.get("cart", ""):
        product = Product.query.filter_by(id=int(product_id)).first()
        quantity = session["cart"][str(product_id)]['quantity']
        product.live = True
        total = quantity * product.price
        num_of_items_in_cart += quantity
        grand_total += total

        items = {"name": product.name, "price": product.price, "image": product.image, "quantity": quantity,
                         "total": round(total, 2), "id": product.id, "stock": product.stock}

        if items not in products:
            products.append(items)

    session["grand_total"] = grand_total
    session["products"] = products
    session.modified = True
    shipping_cost, shipping_fee = process_shipping_fee(grand_total)

    return render_template('cart/cart.html', cart_items=products, grand_total=round(grand_total, 2),
                           shipping_costs=shipping_cost, shipping_fee=shipping_fee, total_items=len(products), form=form)


@cart_app.route("/update/cart-quantity/<int:product_id>/", methods=["POST"])
def update_cart(product_id):

    form = UpdateCartForm()

    if form.validate_on_submit():
        _add_to_cart_helper(product_id, form.quantity.data, update=True)

    return if_url_is_safe_redirect(url_for('cart'), route_func_name_to_redirect_to='cart')

product/views.py
from flask import Blueprint, render_template

from product.forms import AddProductToCartForm
from product.type import ITEM_TYPES
from user.models import Product

product_app = Blueprint('product_app', __name__, url_prefix="/product")

_PER_PAGE = 16


@product_app.route('/<int:product_id>', methods=["GET", "POST"])
def product(product_id):

    product = Product.query.get_or_404(product_id)
    return render_template('products/view-product.html', product=product, form=AddProductToCartForm())


@product_app.route("/trousers/<int:page_number>")
@product_app.route("/trousers")
def get_trousers(page_number=1):

    trousers = Product.query.filter(Product.type == ITEM_TYPES["TROUSERS"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                         page=page_number,
                                                                                                         error_out=False)
    return render_template("products/trousers.html", trousers=trousers, page_number=page_number)


@product_app.route("/tops/<int:page_number>")
@product_app.route("/tops")
def get_tops(page_number=1):

    tops = Product.query.filter(Product.type == ITEM_TYPES["TOPS"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                 page=page_number,
                                                                                                 error_out=False)
    return render_template("products/tops.html", tops=tops, page_number=page_number)


@product_app.route("/sports/wear/<page_number>")
@product_app.route("/sports/wear")
def get_sports_wear(page_number=1):

    sports_wear = Product.query.filter(Product.type == ITEM_TYPES["SPORTS_WEAR"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                               page=page_number,
                                                                                                               error_out=False)
    return render_template("/products/sports_wear.html", sports_wear=sports_wear, page_number=page_number)


@product_app.route("/lingerie/<int:page_number>")
@product_app.route("/lingerie")
def get_lingerie(page_number=1):

    lingeries = Product.query.filter(Product.type == ITEM_TYPES["LINGERIE"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                          page=page_number,
                                                                                                          error_out=False)
    return render_template("products/lingerie.html", lingeries=lingeries, page_number=page_number)


@product_app.route("/shoes/<int:page_number>")
@product_app.route("/shoes")
def get_shoes(page_number=1):
    shoes = Product.query.filter(Product.type == ITEM_TYPES["SHOES"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                   page=page_number, error_out=False)
    return render_template("products/shoes.html", shoes=shoes, page_number=page_number)


@product_app.route("/hoodies/<int:page_number>")
@product_app.route("/hoodies")
def get_hoodies(page_number=1):
    hoodies = Product.query.filter(Product.type == ITEM_TYPES["HOODIES"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                       page=page_number, error_out=False)
    return render_template("products/hoodies.html", hoodies=hoodies, page_number=page_number)


@product_app.route("/hats/<int:page_number>")
@product_app.route("/hats")
def get_hats(page_number=1):
    hats = Product.query.filter(Product.type == ITEM_TYPES["HATS"], Product.live==True).paginate(per_page=_PER_PAGE,
                                                                                                 page=page_number, error_out=False)
    return render_template("products/hats.html", hats=hats, page_number=page_number)

templates/__formhelpers.html
{% macro render_field(field) %}

    <div class="form-group">

        {{ field.label }}
        {{ field(**kwargs) | safe }}

        {% if field.errors %}
            <ul class="text-danger">
                {% for error in field.errors %}
                    <li> {{ error }} </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endmacro %}

templates/__macro_product_display.html
{% macro display_product(products, route, page_number) %}


<div class="row">

	{% for product in products.items %}
	<div class="col-lg-3">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="thumbnail">
				<a href="{{ url_for('product_app.product', product_id=product.id) }}">
					<img src="{{ url_for('static', filename='imgs/' + product.image) }}">
				</a>
				<div class="caption text-center">
					<h4 class="bold">{{ product.name.title() }}</h4>
					<p>
						{{ product.description | truncate(51) }}
					</p>
					<hr />
					<p>
						<a href="{{ url_for('product_app.product', product_id=product.id) }}" class="btn btn-primary btn-sm">
							<i class="glyphicon glyphicon-eye-open"></i> View
						</a>

						{% if product.stock > 0 %}
						<a href="{{ url_for('cart_app.add_one_item_to_cart', product_id=product.id) }}" class="btn btn-default btn-sm">
							<i class="glyphicon glyphicon-shopping-cart"></i> Quick cart add
						</a>

						{% endif %}
					</p>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}


</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center pagination pagination-md">

      {% if products.has_prev %}
           <li class="page-item disabled">
               <a class="page-link" href="{{ url_for(route,
                                  page_number=products.prev_num) }}" tabindex="-1">Previous</a>
           </li>
      {% endif %}
      {% for page in products.iter_pages() %}
            {% if page %}
                <li class="page-item"><a class="page-link" href="{{ url_for(route, page_number=page) }}">{{ page }}</a></li>
            {% else %}
                <span class=ellipsis>…</span>
            {% endif %}
      {% endfor %}

      {% if products.has_next %}
        <li class="page-item"><a class="page-link" href="{{ url_for(route, page_number=products.next_num) }}">Next</a></li>
      {% endif %}
  </ul>
</nav>


{% endmacro %}

templates/_flash_message.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class=flashes>
                {% for message in messages %}
                  <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>

  {% endif %}
{% endwith %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='bs/css/flatly.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
    </head>
    <body>
        {% if admin %}
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('home_app.home') }}">Super Store</a>
                </div>
        
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">


                        <li>
                            <a href="{{ url_for('home_app.home') }}"><i class="glyphicon glyphicon-chevron-left"></i> Back To Front</a>
                        </li>

                        {% if session.admin %}
                             <li>
                                <a href="{{ url_for('admin_app.add') }}"><i class="glyphicon glyphicon-plus-sign"></i> Add Product</a>
                             </li>
                             <li>
                                <a href="{{ url_for('admin_app.admin_logout') }}"><i class="glyphicon glyphicon-plus-sign"></i> Welcome, Admin | Logout</a>
                             </li>
                            {% else %}
                                <li>
                                <a href="{{ url_for('admin_app.admin_login') }}"><i class="glyphicon glyphicon-plus-sign"></i> Admin Login</a>
                                </li>
                        {% endif %}

                    </ul>
                </div><!-- /.navbar-collapse -->


            </div>
        </nav>
        {% else %}
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->


                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                     <!-- Collect the nav links, forms, and other content for toggling -->

                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{{ url_for('home_app.home') }}"><i class="glyphicon glyphicon-dashboard"></i> Super store</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admin_app.admin') }}"><i class="glyphicon glyphicon-dashboard"></i> Admin Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ url_for('product_app.get_trousers') }}"><i class="glyphicon glyphicon-dashboard"></i> Trousers</a>
                        </li>
                        <li>
                            <a href="{{ url_for('product_app.get_tops') }}"><i class="glyphicon glyphicon-dashboard"></i> Tops</a>
                        </li>
                        <li>
                            <a href="{{ url_for('product_app.get_sports_wear') }}"><i class="glyphicon glyphicon-dashboard"></i> Sports Wear</a>
                        </li>
                        <li>
                            <a href="{{ url_for('product_app.get_lingerie') }}"><i class="glyphicon glyphicon-dashboard"></i> Lingerie</a>
                        </li>
                        <li>
                            <a href="{{ url_for('product_app.get_shoes') }}"><i class="glyphicon glyphicon-dashboard"></i> Shoes</a>
                        </li>
                        <li>
                            <a href="{{ url_for('product_app.get_hats') }}"><i class="glyphicon glyphicon-dashboard"></i> Hats</a>
                        </li>

                        <li>
                            <a href="{{ url_for('product_app.get_hoodies') }}"><i class="glyphicon glyphicon-dashboard"></i> Hoodies</a>
                        </li>

                        <li>
                            {% if session.admin %}
                                <a href="{{ url_for('admin_app.admin_logout') }}"><i class="glyphicon glyphicon-plus-sign"></i> (Hi, Admin | Logout)</a>
                            {% else %}
                                <a href="{{ url_for('admin_app.admin_login') }}"><i class="glyphicon glyphicon-plus-sign"></i> Admin Login</a>
                            {% endif %}
                        </li>


                    </ul>
                </div><!-- /.navbar-collapse -->


                </div>
        
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active">
                            <a href="{{ url_for('cart_app.cart') }}">

                                {% if session.num_of_items %}
                                    <i class="glyphicon glyphicon-shopping-cart"></i> Cart ({{ session.num_of_items }})
                                {% elif session and session.num_of_items and session.num_of_items > 100 %}
                                    <i class="glyphicon glyphicon-shopping-cart"></i> Cart (100+)
                                {% else %}
                                    <i class="glyphicon glyphicon-shopping-cart"></i> Cart (0)

                                {% endif %}
                            </a>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
        {% endif %}

        <div class="container" id="page">

        {% block body %}{% endblock %}
            
            <footer>
                <div class="row pad">
                    <div class="col-lg-12 text-center">
                        Copyright &copy; 2020 <strong>Egbie's Super Store</strong>
                    </div>
                </div>


            </footer>
        </div>

        <!-- jQuery -->
        <script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
        <!-- Bootstrap JavaScript -->
        <script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>

    </body>
</html>

templates/carosal_nav.html
<div class="row">
	<div class="col-lg-12">
		<div id="carousel-id" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carousel-id" data-slide-to="0" class=""></li>
				<li data-target="#carousel-id" data-slide-to="1" class=""></li>
			</ol>
			<div class="carousel-inner">
				<div class="item active" style="height: 300px;">
					<img alt="First slide" src="{{ url_for('static', filename='imgs/1.jpg') }}" style="width: 100%;">
					<div class="container">
						<div class="carousel-caption">
							<h1>Amazing Autumn Wears</h1>
							<p>
								Get the most trendy outfits to go with the season
							</p>
						</div>
					</div>
				</div>
				<div class="item" style="height: 300px;">
					<img alt="Second slide" src="{{ url_for('static', filename='imgs/2.jpg') }}" style="width: 100%;">
					<div class="container">
						<div class="carousel-caption">
							<h1>Amazing Autumn Wears</h1>
							<p>
								Get the most trendy outfits to go with the season
							</p>
						</div>
					</div>
				</div>
			</div>
			<a class="left carousel-control" href="#carousel-id" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
			<a class="right carousel-control" href="#carousel-id" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
		</div>
	</div>
</div>
</div>